name: 'Composite Action Example'
description: 'A composite action to checkout code and set up Node.js'
runs:
  using: 'composite'
  steps:
    - id: action_relative_path
      run: |
        action_path=$(node -p 'require("path").relative(process.env.GITHUB_WORKSPACE, "${{ github.action_path }}")')
        echo "action_path=${action_path}" >> "$GITHUB_OUTPUT"
      shell: bash
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: ${{ steps.action_relative_path.outputs.action_path }}/.nvmrc
