name: 'Composite Action Example'
description: 'A composite action to checkout code and set up Node.js'
inputs:
  node-version-file:
    description: 'Path to the Node version file'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Node.js
      uses: gowridurgad/setup-node-fork@testing-aparnas-changes
      with:
        node-version-file: ${{ github.action_repository}}./nvmrc
