name: 'Composite Action Example'
description: 'A composite action to checkout code and set up Node.js'
runs:
  using: 'composite'
  steps:
     - name: Checkout code
       uses: actions/checkout@v4
     - name: Set up Node.js
       uses: gowridurgad/setup-node-fork@absolute-path
       with:
         node-version-file: ${{ github.workspace }}/.nvmrc
   
