name: 'Composite Action Example'
description: 'A composite action to checkout code and set up Node.js'
inputs:
  node-version-file:
    description: 'Path to the Node version file'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Read .nvmrc
      run: echo "::set-output name=NVMRC::$(cat .nvmrc)"
      id: nvm
      shell: bash
    
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
