name: cacheinvalid
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        cache: 'poetry'
    - run: poetry install
    - name: Check Poetry Python version
      run: poetry env info
   
