name: direct Action 
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: gowridurgad/setup-node-fork@absolute-path
        with:
          node-version-file: ${{ github.action_path }}/.nvmrc
