name: goissue477

on:
  workflow_dispatch:

jobs:
  macosCheck:
    runs-on: macos-latest
  
    
    strategy:
      matrix:
        go: ['1.18'] 
        os: ['darwin']
        arch: ['amd64']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
          go-version: ${{ matrix.go }}
    - name: 'Test on [darwin] arch [amd64]'
      if: ${{ matrix.os == 'darwin' && contains(fromJson('["amd64"]'), matrix.arch) }}
      env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
      run: |
          echo ${CGO_ENABLED}
          go env CGO_ENABLED
          
          
         
