name: goissue477

on:
  workflow_dispatch:

jobs:
  macosCheck:
    runs-on: macOS-latest
    
    strategy:
      matrix:
        go: ['1.18'] 
        os: ['macos']
        arch: ['amd64']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
          go-version: ${{ matrix.go }}
    - name: 'Test on [darwin] arch [amd64]'
      if: ${{ matrix.os == 'macos' && contains(fromJson('["amd64"]'), matrix.arch) }}
      env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
      run: |
          echo "CGO_ENABLED: ${CGO_ENABLED}"
          echo "GOOS: ${GOOS}"
          echo "GOARCH: ${GOARCH}"
          go env CGO_ENABLED
          go env
