name: node yarn cache

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['macos-12', 'macos-13']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Restore Yarn Cache
        if: cache-hit != 'true'
        run: |
          mkdir -p ~/.cache/yarn
          cp -R /path/to/cache ~/.cache/yarn
      - name: Use node
        run: |
          node --version
          yarn --version
          yarn install
      - name: Save Yarn Cache
        if: always()
        run: |
          mkdir -p /path/to/cache
          cp -R ~/.cache/yarn /path/to/cache
