name: PR-134v

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aparnajyothi-y/setup-node@add-mirror-url
        with:
          node-version: "21"
          mirrorURL: "https://nodejs.org/dist/"
     
     
