name: venkata

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gowridurgad/setup-node@gowri-36
        with:
          node-version: "21.0.0"
          mirror-url: "https://nodejs.org/dist/"
      - name: Print Node.js version
        run: node -v
