name: venkata

on:
  
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gowridurgad/setup-node@siva-devi
        with:
          node-version: 16
          mirror-url : "node-v16.13.2-linux-armv7l.tar.xz"
    
