name: node yarn cache

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['macos-12', 'macos-13']
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Check for Yarn cache
        id: check-cache
        run: |
          if [ -d "$HOME/.cache/yarn" ]; then
            echo "Cache found"
            echo "cache-hit=true" >> $GITHUB_ENV
          else
            echo "Cache not found"
            echo "cache-hit=false" >> $GITHUB_ENV
          fi

      - name: Use node
        run: |
          node --version
          yarn --version
          yarn install
        if: env.cache-hit != 'true'

      - name: Save Yarn cache
        if: env.cache-hit != 'true'
        run: |
          mkdir -p $HOME/.cache/yarn
          cp -R node_modules $HOME/.cache/yarn
