name: Test Registry URL Issue

on: 
   workflow_dispatch:

jobs:
  test-setup-node:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Node.js (default registry)
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org/'

    - name: Install dependencies
      run: npm ci

    - name: Setup Node.js (GPR registry)
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: 'https://npm.pkg.github.com/'

    - name: Publish to GPR
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.MY_GITHUB}}

    - name: Setup Node.js (npm registry)
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org/'

    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
