name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          check-latest: true
