name: issue#1363
on:
   workflow_dispatch
  

jobs:
  Validate-Example-Taskfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: priyagupta108/setup-node@enable-npm-cache-default
        with:
          node-version: '24'
          cache: 'npm'
      - run: npm install 

   
