name: Node yarn cache

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
        
          - os: "macos-13"
            architecture: "x64"
          - os: "macos-12"
            architecture: "x64"
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.target.os }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: pengx17/setup-node@main
        with:
          node-version: 20.x
          cache: 'yarn'

      - name: Use node
        run: |
          node --version
          yarn --version
          yarn install
