name: node yarn cache

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        os: ['ubuntu-latest', 'ubuntu-20.04']
    steps:
      - uses: actions/checkout@v4

      - name: Create unique cache file
        run: |
          echo "${{ github.run_id }}-${{ matrix.os }}-$(date +%s)" > .cache-key
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'
          cache-dependency-path: |
            **/yarn.lock
            .cache-key
      - name: Use node
        run: |
          node --version
          yarn --version
          yarn install
