name: issue914-toolcache

on:
  workflow_dispatch:

jobs:
  test-python:
    name: Test Python pip install
    runs-on: self-hosted
    
    steps:
      - name: Github Actions Context Information
        uses: SiemaApplications-attic/vossloh-gh-actions/debug/show-github-context@v7

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Show environment variables
        run: env

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-dev libglib2.0-dev libcairo2-dev

      - name: Python package install
        run: pip install PyGObject
