
name: MirrorURL testing

on:
  workflow_dispatch:

jobs:
  setup-node:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js with mirrorURL
        uses: aparnajyothi-y/setup-node@add-mirror-url
        with:
          node-version: '22.0.0-rc.1'
          mirror-url: 'https://mirrors.dotsrc.org/nodejs/rc/'
