name: MirrorURL testing

on:
  workflow_dispatch:

jobs:
  setup-node:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13]
        node-versions: [20]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js with mirrorURL
        uses: actions/setup-node@v4
        with:
          node-version : ${{  matrix.node-versions }}
          check-latest: true
