name: node yarn cache

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['macos-12', 'macos-13']
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock-${{ github.run_id }}'
      
      - name: Use node
        run: |
          node --version
          yarn --version
          yarn install
