name: issue914-toolcache

on:
  workflow_dispatch:

jobs:
  test-python:
    name: Test Python pip install
    runs-on: self-hosted
    
    steps:
      - name: Github Actions Context Information
        uses: SiemaApplications-attic/vossloh-gh-actions/debug/show-github-context@v7

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Set CPATH environment variable
        run: |
          export CPATH=$(pwd)/_work/_tool/Python/3.10.14/x64/include/python3.10
          echo "CPATH set to $CPATH"
          
      - name: Show environment variables
        run: env

      - name: Python package install
        run: pip install PyGObject
