name: testing1285
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install deps (requires venv)
        # env:
        #   PIP_REQUIRE_VIRTUALENV: "1"
        # run: |
        #   python -m venv .venv
        #   . .venv/bin/activate
        #   pip install -r requirements.txt
        run: |
           python -m venv .venv
           source .venv/bin/activate
            pip install -r requirements.txt
        env:
             PIP_REQUIRE_VIRTUALENV: 1
