name: testing1285
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    env:
      PIP_REQUIRE_VIRTUALENV: "1" 
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6
      with:
        python-version: '3.11'
    - name: Install deps (will fail outside venv)
      run: pip install -r requirements.txt

