name: Python Setup and Pip Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11','3.12', '3.13']

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.python-version}}
        cache: 'pip' 

    - name: Display Python version
      run: python --version

    - name: Check pip
      run: |
        which pip
        pip --version
