name: isssue

on: 
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      run: |
        PYTHON_VERSION=3.12
        RUNNER_TOOL_CACHE=$(Agent.ToolsDirectory) # this is set by the runner
        mkdir -p ${RUNNER_TOOL_CACHE}/Python/${PYTHON_VERSION}/x64
        curl -O https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tgz
        tar -xzf Python-${PYTHON_VERSION}.tgz --directory ${RUNNER_TOOL_CACHE}/Python/${PYTHON_VERSION}/x64
        touch ${RUNNER_TOOL_CACHE}/Python/${PYTHON_VERSION}/x64.complete
        rm -f Python-${PYTHON_VERSION}.tgz
        echo "${RUNNER_TOOL_CACHE}/Python/${PYTHON_VERSION}/x64/bin" >> $GITHUB_PATH 

    - name: Verify Python Installation
      run: |
        python --version
