name: poetryTest

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install Poetry
      run: python -m pip install poetry
    - name: Check Poetry Python version
      run: poetry env info
    - name: Cache Poetry dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
         ${{ runner.os }}-poetry-
    - name: Install dependencies
      run: poetry install
    - name: Check Poetry Python version
      run: poetry env info
