name: poetryTest

on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pipx install poetry==1.8.3
    - run: echo "/root/.local/bin" >> $GITHUB_PATH
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: poetry
    - run: pipx install poetry==1.8.3
    - run: poetry install
      working-directory: app
