name: sapmachine

on:
   workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gowridurgad/setup-java-fork@testing-snap
        with:
           distribution: 'sapmachine'
           java-version: '21'
           cache: 'maven'
         
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
