name: testing1206

on:
  workflow_dispatch:



jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        check-latest: true

    
