name: Insert Outdated Node.js Version

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-node:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Old Node.js Version
      run: |
        mkdir -p $HOME/custom/cache/node
        curl -o $HOME/custom/cache/node/node-v12.18.3-linux-x64.tar.xz https://nodejs.org/dist/v12.18.3/node-v12.18.3-linux-x64.tar.xz
        tar -xf $HOME/custom/cache/node/node-v12.18.3-linux-x64.tar.xz -C $HOME/custom/cache/node
      shell: bash

    - name: Add Node.js to PATH
      run: echo "$HOME/custom/cache/node/node-v12.18.3-linux-x64/bin" >> $GITHUB_PATH

    - name: Verify Node.js Version
      run: node -v

    - name: Set up Node.js with check-latest
      uses: actions/setup-node@v4
      with:
        node-version: '12'
        check-latest: true

    - name: Verify Latest Node.js Version
      run: node -v
